from __future__ import annotations

THRESHOLDS = {
    "hot_lufs": -9.0,
    "quiet_lufs": -18.0,
    "stream_target_lufs": -14.0,
    "true_peak_ceiling": -1.0,
    "peak_ceiling": -0.3,
    "minimum_crest_db": 8.0,
    "minimum_plr_db": 8.0,
    "minimum_dynamic_proxy_db": 7.0,
    "clipping_major": 8,
    "clipping_minor": 1,
    "stereo_width_low": 0.08,
    "stereo_width_high": 0.55,
    "stereo_balance_db": 1.5,
    "correlation_warning": 0.05,
    "negative_correlation_ratio": 0.08,
    "mono_loss_warning_db": 1.5,
    "low_mid_ratio_high": 0.24,
    "presence_ratio_high": 0.16,
    "sibilance_ratio_high": 0.11,
    "air_ratio_low": 0.05,
    "rolloff_low_hz": 14000.0,
    "low_freq_ratio_high": 0.36,
    "low_freq_ratio_low": 0.09,
    "sub_to_bass_ratio_high": 1.05,
    "sub_to_bass_ratio_low": 0.2,
    "low_freq_side_ratio_high": 0.22,
    "noise_floor_high_dbfs": -45.0,
    "leading_silence_long": 3.0,
    "trailing_silence_long": 5.0,
    "dc_offset_high": 0.01,
    "hum_ratio_high": 0.33,
    "click_count_high": 6,
}

WEIGHTS = {
    "loudness": 1.2,
    "dynamics": 1.0,
    "clipping": 1.2,
    "stereo": 0.9,
    "phase": 1.0,
    "spectral_balance": 1.0,
    "low_end": 0.9,
    "high_end": 0.8,
    "noise": 0.8,
    "technical_hygiene": 0.7,
}
